site_name: MEJS-Framework 使用文档
theme:
  name: material
  #custom_dir: overrides
  language: zh
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - content.code.annotate # 代码块注释
  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono

repo_url: https://github.com/Miaow233/MEJS-Framework
repo_name: MEJS-Framework
edit_uri: blob/main/docs/

copyright: Copyright &copy; Medic Project 2020-2022.

extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=n87gGGbj
      name: Medic 交流群
    - icon: material/compass
      link: https://jq.qq.com/?_wv=1027&k=K5csid5C
      name: MEJS 开发群
    - icon: fontawesome/brands/github
      link: https://github.com/Miaow233/MEJS-Framework
      name: GitHub 组织
  search:
    language: jp # 不支持中文，改成日文好像能搜到一部分中文了（无语）

# extra_css:
#   - https://unpkg.com/botui/build/botui.min.css
#   - https://unpkg.com/botui/build/botui-theme-default.css
# extra_javascript:
#   - https://cdn.jsdelivr.net/vue/latest/vue.min.js
#   - https://unpkg.com/botui/build/botui.min.js

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition # 提示块
  - footnotes # 脚注
  - pymdownx.snippets
  - pymdownx.superfences # 代码嵌套在列表里
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.highlight
  - pymdownx.magiclink # 自动识别超链接
  - toc: # 目录, 锚点
      permalink: true
      title: 目录
  - codehilite: # 代码高亮, 显示行号
      guess_lang: false
      linenums: true
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 主页:
      - index.md
      - quickstart.md
      - 指令系统: cac.md
      - 插件系统: plugin-manager.md
      - 接口一览: type/index.html
      - 更新说明: changelog.md
  - Medic 文档:
      - 介绍: Medic/index.md
      - 快速开始: Medic/quickstart.md
      - 基础:
          - 词库介绍: Medic/basic/dic.md
          - 词条介绍: Medic/basic/entry.md
          - 常量介绍: Medic/basic/constant.md
          - 模块介绍: Medic/basic/mod.md
          - 变量介绍: Medic/basic/value.md
          - 内置模块 System: Medic/basic/system.md
      - 参考:
          - 内置 API 类: Medic/reference/api.md
          - 内置 Toolkit 类: Medic/reference/toolkit.md
          - 使用 JavaScript:
              - 内置 JavaScript 支持库: Medic/reference/libs/javascript.md
              - MEJS2 词库: /
          - 画图库: Medic/reference/libs/draw.md
          - 自定义 Dex 库函数: Medic/reference/libs/java.md
