site_name: MEJS 使用文档
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  search:
    language: jp # 不支持中文，改成日文好像能搜到一部分中文了（无语）

nav:
  - 主页: index.md
  - 接口一览: 接口一览.md
