public class java.io.File
{
    // Constructors
    public java.io.File(java.io.File, java.lang.String);
    public java.io.File(java.lang.String);
    public java.io.File(java.lang.String, int);
    public java.io.File(java.lang.String, java.io.File);
    public java.io.File(java.lang.String, java.lang.String);
    public java.io.File(java.net.URI);
    // Methods
    public static java.io.File createTempFile(java.lang.String, java.lang.String);
    public static java.io.File createTempFile(java.lang.String, java.lang.String, java.io.File);
    private static java.io.File generateTempFile(java.lang.String, java.lang.String, java.io.File);
    public static [Ljava.io.File; listRoots();
    private synchronized void readObject(java.io.ObjectInputStream);
    private static java.lang.String slashify(java.lang.String, boolean);
    private synchronized void writeObject(java.io.ObjectOutputStream);
    public boolean canExecute();
    public boolean canRead();
    public boolean canWrite();
    public int compareTo(java.io.File);
    public volatile int compareTo(java.lang.Object);
    public boolean createNewFile();
    public boolean delete();
    public void deleteOnExit();
    public boolean equals(java.lang.Object);
    public boolean exists();
    public java.io.File getAbsoluteFile();
    public java.lang.String getAbsolutePath();
    public java.io.File getCanonicalFile();
    public java.lang.String getCanonicalPath();
    public long getFreeSpace();
    public java.lang.String getName();
    public java.lang.String getParent();
    public java.io.File getParentFile();
    public java.lang.String getPath();
    int getPrefixLength();
    public long getTotalSpace();
    public long getUsableSpace();
    public int hashCode();
    public boolean isAbsolute();
    public boolean isDirectory();
    public boolean isFile();
    public boolean isHidden();
    final boolean isInvalid();
    public long lastModified();
    public long length();
    public [Ljava.lang.String; list();
    public [Ljava.lang.String; list(java.io.FilenameFilter);
    public [Ljava.io.File; listFiles();
    public [Ljava.io.File; listFiles(java.io.FileFilter);
    public [Ljava.io.File; listFiles(java.io.FilenameFilter);
    public boolean mkdir();
    public boolean mkdirs();
    public boolean renameTo(java.io.File);
    public boolean setExecutable(boolean);
    public boolean setExecutable(boolean, boolean);
    public boolean setLastModified(long);
    public boolean setReadOnly();
    public boolean setReadable(boolean);
    public boolean setReadable(boolean, boolean);
    public boolean setWritable(boolean);
    public boolean setWritable(boolean, boolean);
    public java.lang.String toString();
    public java.net.URI toURI();
    public java.net.URL toURL();
    // Fields
    private java.lang.String path;
    private transient int prefixLength;
    private transient java.io.File$PathStatus status;
    static final boolean -assertionsDisabled;
    private static final java.io.FileSystem fs;
    public static final java.lang.String pathSeparator;
    public static final char pathSeparatorChar;
    public static final java.lang.String separator;
    public static final char separatorChar;
    private static final long serialVersionUID;
}