import { CharacterGender, CharacterNationality } from './character'
const CARD_MAGIC_RANGE_MAPPING = {
  五谷丰登: -1,
  桃园结义: -1,
  南蛮入侵: -1,
  万箭齐发: -1,
  决斗: 1,
  无中生有: 1,
  顺手牵羊: 1,
  过河拆桥: 1,
  借刀杀人: 2,
  无懈可击: 1,
  乐不思蜀: 1,
  闪电: 1,
}

const CARD_CONTERACT_MAPPING = {
  杀: '闪',
  五谷丰登: '无懈可击',
  桃园结义: '无懈可击',
  南蛮入侵: '无懈可击',
  万箭齐发: '无懈可击',
}

const EQUIP_RANGE_MAPPING = {
  诸葛连弩: 1,
  寒冰剑: 2,
  雌雄双股剑: 2,
  清鉷剑: 2,
  青龙偃月刀: 3,
  丈八蛇矛: 3,
  贯石斧: 4,
  方天画戟: 5,
  麒麟弓: 5,
}

const EQUIP_TYPE_MAPPING = {
  /* 0:武器, 1:防具, 2:+1马, 3:-1马 */
  诸葛连弩: 0,
  雌雄双股剑: 0,
  青釭剑: 0,
  青龙偃月刀: 0,
  丈八蛇矛: 0,
  贯石斧: 0,
  方天画戟: 0,
  麒麟弓: 0,
  寒冰剑: 0,
  八卦阵: 1,
  仁王盾: 1,
  绝影: 2,
  的卢: 2,
  爪黄飞电: 2,
  赤兔: 3,
  大宛: 3,
  紫骍: 3,
}
export const IDENTITY_MAPPING = {
  /* 人数对应角色数量 */
  /* 0: "主公", 1: "忠臣", 2: "内奸", 3: "反贼" */
  2: [0, 2],
  4: [0, 1, 2, 3],
}

/** 名称 体力 技能 势力 性别 */
export const Character = [
  ['曹操', 4, ['护驾', '奸雄'], CharacterNationality.Wei, CharacterGender.Male],
  ['张辽', 4, ['突袭'], CharacterNationality.Wei, CharacterGender.Male],
  ['郭嘉', 3, ['天妒', '遗计'], CharacterNationality.Wei, CharacterGender.Male],
  ['夏侯淳', 4, ['刚烈'], CharacterNationality.Wei, CharacterGender.Male],
  ['司马懿', 3, ['反馈', '鬼才'], CharacterNationality.Wei, CharacterGender.Male],
  ['许褚', 4, ['裸衣'], CharacterNationality.Wei, CharacterGender.Male],
  ['甄姬', 3, ['洛神', '倾国'], CharacterNationality.Wei, CharacterGender.Female],
  ['刘备', 4, ['激将', '仁德'], CharacterNationality.Shu, CharacterGender.Male],
  ['关羽', 4, ['武圣'], CharacterNationality.Shu, CharacterGender.Male],
  ['张飞', 4, ['咆哮'], CharacterNationality.Shu, CharacterGender.Male],
  ['赵云', 4, ['龙胆'], CharacterNationality.Shu, CharacterGender.Male],
  ['马超', 4, ['马术', '铁骑'], CharacterNationality.Shu, CharacterGender.Male],
  ['诸葛亮', 3, ['观星', '空城'], CharacterNationality.Shu, CharacterGender.Male],
  ['黄月英', 3, ['集智', '奇才'], CharacterNationality.Shu, CharacterGender.Female],
  ['孙权', 4, ['救援', '制衡'], CharacterNationality.Wu, CharacterGender.Male],
  ['周瑜', 3, ['反间', '英姿'], CharacterNationality.Wu, CharacterGender.Male],
  ['吕蒙', 4, ['克己'], CharacterNationality.Wu, CharacterGender.Male],
  ['陆逊', 3, ['连营', '谦逊'], CharacterNationality.Wu, CharacterGender.Male],
  ['甘宁', 4, ['奇袭'], CharacterNationality.Wu, CharacterGender.Male],
  ['黄盖', 4, ['苦肉'], CharacterNationality.Wu, CharacterGender.Male],
  ['大乔', 3, ['国色', '流离'], CharacterNationality.Wu, CharacterGender.Female],
  ['孙尚香', 3, ['结姻', '枭姬'], CharacterNationality.Wu, CharacterGender.Female],
  ['吕布', 4, ['无双'], CharacterNationality.Qun, CharacterGender.Male],
  ['华佗', 3, ['急救', '青囊'], CharacterNationality.Qun, CharacterGender.Male],
  ['貂蝉', 3, ['闭月', '离间'], CharacterNationality.Qun, CharacterGender.Female],
]

/*
 * 卡牌数据
 * 'color' : 方块: 0, 红桃: 1, 梅花: 2, 黑桃: 3;
 */
export const CARD = [
  { name: '杀', color: 3, digit: '7' },
  { name: '杀', color: 3, digit: '8' },
  { name: '杀', color: 3, digit: '8' },
  { name: '杀', color: 3, digit: '9' },
  { name: '杀', color: 3, digit: '9' },
  { name: '杀', color: 3, digit: '10' },
  { name: '杀', color: 3, digit: '10' },
  { name: '杀', color: 2, digit: '2' },
  { name: '杀', color: 2, digit: '3' },
  { name: '杀', color: 2, digit: '4' },
  { name: '杀', color: 2, digit: '5' },
  { name: '杀', color: 2, digit: '6' },
  { name: '杀', color: 2, digit: '7' },
  { name: '杀', color: 2, digit: '8' },
  { name: '杀', color: 2, digit: '8' },
  { name: '杀', color: 2, digit: '9' },
  { name: '杀', color: 2, digit: '9' },
  { name: '杀', color: 2, digit: '10' },
  { name: '杀', color: 2, digit: '10' },
  { name: '杀', color: 2, digit: '11' },
  { name: '杀', color: 2, digit: '11' },
  { name: '杀', color: 1, digit: '2' },
  { name: '杀', color: 1, digit: '2' },
  { name: '杀', color: 1, digit: '13' },
  { name: '杀', color: 0, digit: '6' },
  { name: '杀', color: 0, digit: '7' },
  { name: '杀', color: 0, digit: '8' },
  { name: '杀', color: 0, digit: '9' },
  { name: '杀', color: 0, digit: '10' },
  { name: '杀', color: 0, digit: '13' },
  { name: '闪', color: 1, digit: '2' },
  { name: '闪', color: 1, digit: '2' },
  { name: '闪', color: 1, digit: '13' },
  { name: '闪', color: 0, digit: '2' },
  { name: '闪', color: 0, digit: '2' },
  { name: '闪', color: 0, digit: '3' },
  { name: '闪', color: 0, digit: '4' },
  { name: '闪', color: 0, digit: '5' },
  { name: '闪', color: 0, digit: '6' },
  { name: '闪', color: 0, digit: '7' },
  { name: '闪', color: 0, digit: '8' },
  { name: '闪', color: 0, digit: '9' },
  { name: '闪', color: 0, digit: '10' },
  { name: '闪', color: 0, digit: '11' },
  { name: '闪', color: 0, digit: '11' },
  { name: '桃', color: 1, digit: '3' },
  { name: '桃', color: 1, digit: '4' },
  { name: '桃', color: 1, digit: '6' },
  { name: '桃', color: 1, digit: '7' },
  { name: '桃', color: 1, digit: '8' },
  { name: '桃', color: 1, digit: '9' },
  { name: '桃', color: 1, digit: '12' },
  { name: '桃', color: 0, digit: '12' },
  // { name: '诸葛连弩', color: 2, digit: '1' },
  // { name: '诸葛连弩', color: 0, digit: '1' },
  // { name: '雌雄双股剑', color: 3, digit: '2' },
  // { name: '青釭剑', color: 3, digit: '6' },
  // { name: '青龙偃月刀', color: 3, digit: '5' },
  // { name: '丈八蛇矛', color: 3, digit: '12' },
  // { name: '贯石斧', color: 0, digit: '5' },
  // { name: '方天画戟', color: 0, digit: '12' },
  // { name: '麒麟弓', color: 1, digit: '5' },
  // { name: '八卦阵', color: 3, digit: '2' },
  // { name: '八卦阵', color: 2, digit: '2' },
  // { name: '绝影', color: 3, digit: '5' },
  // { name: '的卢', color: 2, digit: '5' },
  // { name: '爪黄飞电', color: 1, digit: '13' },
  // { name: '赤兔', color: 1, digit: '5' },
  // { name: '大宛', color: 3, digit: '13' },
  // { name: '紫骍', color: 0, digit: '13' },
  // { name: '五谷丰登', color: 1, digit: '3' },
  // { name: '五谷丰登', color: 1, digit: '4' },
  // { name: '桃园结义', color: 1, digit: '1' },
  // { name: '南蛮入侵', color: 3, digit: '7' },
  // { name: '南蛮入侵', color: 3, digit: '13' },
  // { name: '南蛮入侵', color: 2, digit: '7' },
  // { name: '万箭齐发', color: 1, digit: '1' },
  // { name: '决斗', color: 3, digit: '1' },
  // { name: '决斗', color: 2, digit: '1' },
  // { name: '决斗', color: 0, digit: '1' },
  // { name: '无中生有', color: 1, digit: '7' },
  // { name: '无中生有', color: 1, digit: '8' },
  // { name: '无中生有', color: 1, digit: '9' },
  // { name: '无中生有', color: 1, digit: '11' },
  // { name: '顺手牵羊', color: 3, digit: '3' },
  // { name: '顺手牵羊', color: 3, digit: '4' },
  // { name: '顺手牵羊', color: 3, digit: '11' },
  // { name: '顺手牵羊', color: 0, digit: '4' },
  // { name: '顺手牵羊', color: 0, digit: '1' },
  // { name: '过河拆桥', color: 3, digit: '3' },
  // { name: '过河拆桥', color: 3, digit: '4' },
  // { name: '过河拆桥', color: 3, digit: '12' },
  // { name: '过河拆桥', color: 2, digit: '3' },
  // { name: '过河拆桥', color: 2, digit: '4' },
  // { name: '过河拆桥', color: 1, digit: '12' },
  // { name: '借刀杀人', color: 2, digit: '12' },
  // { name: '借刀杀人', color: 2, digit: '13' },
  // { name: '无懈可击', color: 3, digit: '11' },
  // { name: '无懈可击', color: 2, digit: '12' },
  // { name: '无懈可击', color: 2, digit: '13' },
  // { name: '乐不思蜀', color: 3, digit: '6' },
  // { name: '乐不思蜀', color: 2, digit: '6' },
  // { name: '乐不思蜀', color: 1, digit: '6' },
  // { name: '闪电', color: 3, digit: '1' },
  // { name: '寒冰剑', color: 3, digit: '2' },
  // { name: '仁王盾', color: 2, digit: '2' },
  // { name: '闪电', color: 1, digit: '12' },
  // { name: '无懈可击', color: 0, digit: '12' },
]

const SKILL_EXPLANATION_MAPPING = {
  护驾: '主公技，当你需要使用（或打出）一张【闪】时，你可以发动护驾。所有魏势力角色按行动顺序依次选择是否打出一张【闪】“提供”给你（视为由你使用或打出），直到有一名角色或没有任何角色决定如此做时为止',
  奸雄: '你可以立即获得对你造成伤害的牌',
  突袭: '摸牌阶段，你可以放弃摸牌，然后从至多两名（至少一名）角色的手牌里各抽取一张牌★摸牌阶段，你一旦发动突袭，就不能从牌堆获得牌★只剩一名其他角色时，你就只能选择这一名角色★若此时其他任何人都没有手牌，你就不能发动突袭',
  天妒: '在你的判定牌生效时，你可以立即获得它',
  遗计: '你每受到1点伤害，可摸两张牌，将其中的一张交给任意一名角色，然后将另一张交给任意一名角色',
  刚烈: '你每受到一次伤害，可进行一次判定：若结果不为红桃，则目标来源必须进行二选一：弃两张手牌或受到你对其造成的1点伤害',
  反馈: '你可以立即从对你造成伤害的来源处获得一张牌★一次无论受到多少点伤害，只能获得一张牌，若选择手牌则从对方手里随机抽取，选择面前的装备则由你任选',
  鬼才: '在任意角色的判定牌生效前，你可以打出一张手牌代替之',
  裸衣: '摸牌阶段，你可以少摸一张牌；若如此做，该回合的出牌阶段，你使用【杀】或【决斗】（你为伤害来源时）造成的伤害+1',
  洛神: '回合开始阶段，你可以进行判定：若为黑色，立即获得此生效后的判定牌，并可以再次使用洛神――如此反复，直到出现红色或你不愿意判定了为止',
  倾国: '你可以将你的黑色手牌当【闪】使用（或打出）★使用倾国时，仅改变牌的类别（名称）和作用，而牌的花色和点数不变',
  激将: '主公技，当你需要使用（或打出）一张【杀】时，你可以发动激将。所有蜀势力角色按行动顺序依次选择是否打出一张【杀】“提供”给你（视为由你使用或打出），直到有一名角色或没有任何角色决定如此作时为止 ',
  仁德: '出牌阶段，你可以将任意数量的手牌以任意分配方式交给其他角色，若你给出的牌张数不少于两张时，你回复1点体力★使用仁德技能分出的牌，对方无法拒绝',
  武圣: '你可以将你的任意一张红色牌当【杀】使用或打出★若同时用到当前装备的红色装备效果时，不可把这张装备牌当【杀】来使用或打出★使用武圣时，仅改变牌的类别(名称)和作用，而牌的花色和点数不变',
  咆哮: '出牌阶段，你可以使用任意数量的【杀】',
  龙胆: '你可以将你手牌的【杀】当【闪】、【闪】当【杀】使用或打出。★使用龙胆时，仅改变牌的类别(名称)和作用，而牌的花色和点数不变',
  马术: '锁定技，当你计算与其他角色的距离时，始终-1★马术的效果与装备-1马时效果一样，但你仍然可以装备一匹-1马',
  铁骑: '当你使用【杀】指定一名角色为目标后，你可以进行判定，若结果为红色，此【杀】不可被闪避',
  观星: '回合开始阶段，你可以观看牌堆顶的X张牌（X为存活角色的数量且最多为5），将其中任意数量的牌以任意顺序置于牌堆顶，其余以任意顺序置于牌堆底',
  空城: '锁定技，当你没有手牌时，你不能成为【杀】或【决斗】的目标',
  集智: '每当你使用一张非延时类锦囊时，（在它结算之前）你可以立即摸一张牌',
  奇才: '你使用任何锦囊无距离限制',
  救援: '主公技，锁定技，其他吴势力角色在你濒死状态下对你使用【桃】时，你额外回复1点体力',
  制衡: '出牌阶段,你可以弃掉任意数量的牌,然后摸取等量的牌.每回合限用一次',
  反间: '出牌阶段，你可以令另一名角色选择一种花色，抽取你的一张手牌并亮出，若此牌与所选花色不吻合，则你对该角色造成1点伤害。然后不论结果，该角色都获得此牌。每回合限用一次',
  英姿: '摸牌阶段，你可以额外摸一张牌',
  克己: '若你于出牌阶段未使用或打出过任何一张【杀】，你可以跳过此回合的弃牌阶段',
  连营: '每当你失去最后一张手牌时，可立即摸一张牌',
  谦逊: '锁定技，你不能成为【顺手牵羊】和【乐不思蜀】的目标',
  奇袭: '出牌阶段，你可以将你的任意黑色牌当【过河拆桥】使用★这包括自己已装备的牌★使用奇袭时，仅改变牌的类别(名称)和作用，而牌的花色和点数不变',
  苦肉: '出牌阶段，你可以失去一点体力，然后摸两张牌。每回合中，你可以多次使用苦肉★当你失去最后一点体力时，优先结算濒死事件，当你被救活后，你才可以摸两张牌。换言之，你可以用此技能自杀',
  国色: '出牌阶段，你可以将你的任意方块花色的牌当【乐不思蜀】使用',
  流离: '当你成为【杀】的目标时，你可以弃一张牌，并将此【杀】转移给你攻击范围内的另一名角色（该角色不得是【杀】的使用者）',
  结姻: '出牌阶段，你可以弃两张手牌并选择一名受伤的男性角色：你和目标角色各回复1点体力。每回合限用一次★使用结姻的条件是“有受伤的男性角色”，与你是否受伤无关',
  枭姬: '当你失去一张装备区里的牌时，你可以立即摸两张牌',
  无双: '锁定技，你使用【杀】时，目标角色需连续使用两张【闪】才能抵消；与你进行【决斗】的角色每次需连续打出两张【杀】★若对方只有一张【闪】或【杀】则即便使用（打出）了也无效',
  急救: '你的回合外，你可以将你的任意红色牌当【桃】使用',
  青囊: '出牌阶段，你可以主动弃掉一张手牌，令任一目标角色回复1点体力。每回合限用一次',
  闭月: '回合结束阶段，可摸一张牌',
  离间: '出牌阶段，你可以弃一张牌并选择两名男性角色。若如此作，视为其中一名男性角色对另一名男性角色使用一张【决斗】。（此【决斗】不能被【无懈可击】响应）。每回合限用一次',
}

const CARD_COLOR_NUM_MAPPING = {
  color: { 0: 'red', 1: 'red', 2: 'black', 3: 'black' },
  number: {
    1: 'A',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: 'J',
    12: 'Q',
    13: 'K',
  },
}
export const IDENTITY_INDEX_MAPPING = {
  name: { 0: '主公', 1: '忠臣', 2: '内奸', 3: '反贼' },
}

const NUMBER_CHARACHER_MAPPING = {
  1: '一',
  2: '二',
  3: '三',
  4: '四',
  5: '五',
  6: '六',
  7: '七',
  8: '八',
  9: '九',
  10: '十',
}
